import React from "react";
import CourseList from "./components/CourseList";

export const metadata = {
  title: "CouseHub",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div>
      <CourseList />
    </div>
  );
};

export default Page;
